# Generated by Django 4.2 on 2023-04-29 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('publisher_name', models.CharField(max_length=100)),
                ('publisher_age', models.IntegerField()),
                ('page_number', models.IntegerField()),
                ('publish_date', models.DateField()),
                ('sci_fi', models.BooleanField(default=False)),
                ('drama', models.BooleanField(default=False)),
                ('novel', models.BooleanField(default=False)),
            ],
        ),
    ]
